name: Linux

on:
  push:
    branches: [master, workflow-test, app-path]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        run: |
          sudo apt-get update
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get install python3.10
      - name: Install dependencies
        run: |
          sudo apt-get install git python3-gi python3-gi-cairo libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkit2gtk-4.0-37 gir1.2-webkit2-4.0 python3-cairo-dev libwxgtk3.0-gtk3-dev
      - name: Beeware dependencies
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python3 -m pip install -r requirements.txt
      - name: Run tests with
        run: |
          cd src/
          python -m unittest test_app.Test_Profile_Manager.test_swap_xml -v
          python -m unittest test_app.Test_Profile_Manager.test_delete_profile -v
          python -m unittest test_app.Test_Profile_Manager.test_create_profile -v
          python -m unittest test_app.Test_Profile_Manager.test_load_profile -v
          python -m unittest test_app.Test_Profile_Manager.test_get_ethnic -v
          python -m unittest test_app.Test_Profile_Manager.test_switching_profiles_with_invalid_path -v
          python -m unittest test_app.Test_Profile_Manager.test_migrate_function -v
          python -m unittest test_app.Test_XML_Parser -v
          python -m unittest test_app.Test_RTF_Parser -v
          python -m unittest test_app.Test_Config_Manager -v
          python -m unittest test_app.Test_Xml_Writing -v
          python -m unittest test_mapper.Test_Mapper_Generate_Mapping -v
          python -m unittest test_mapper.Test_Mapper_Preserve_Mapping -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_simple -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_all_cases -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_double -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_double_exclusive -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_complete_subset -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_complete_subset_reverse -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_partial_subset -v
          python -m unittest test_mapper.Test_Mapper_Overwrite_Mapping.test_overwrite_mapping_partial_subset_reverse -v
      - name: Build
        run: |
          briefcase create 
          briefcase build 
          #briefcase package
      - name: Save Installer
        uses: actions/upload-artifact@v4
        with:
          name: NewGAN-Manager-Installer-Linux-v1.4.1
          path: |
            views/
            filters/
            linux/NewGAN-Manager-1.4.1-x86_64.AppImage
